
title: My Site Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# For local development or self-hosting you can just
# specify the RubyGem name below.
theme: govuk-jekyll-theme

# Remote theme is required for GitHub Pages publishing
remote_theme: frankieroberto/govuk-jekyll-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"